[mypy]
python_version = 3.14
warn_redundant_casts = True
warn_unreachable = True
warn_unused_configs = True
pretty = True
mypy_path = .
allow_untyped_defs = False
exclude = ^tests/

[mypy-pydantic.*]
follow_imports = skip

[mypy-pydantic.main]
follow_imports = skip
