"""Derive the Pydantic classes, JSON Schema, and SHACL shapes from the LinkML schema.

One source, three generated artifacts, no drift between them. The artifacts are
checked in so that consumers (and CI) need not run LinkML to read them, and
``check_generated_is_current`` is what keeps the checked-in copies honest.
"""

import json
from dataclasses import dataclass
from pathlib import Path

from linkml.generators.jsonschemagen import JsonSchemaGenerator
from linkml.generators.pydanticgen import PydanticGenerator
from linkml.generators.shaclgen import ShaclGenerator

from tapio_register import paths

# The pyrefly suppression has to be the file's first line to cover the file.
# LinkML's output is not written to this project's type-checking standard and is
# not ours to fix; suppressing keeps `pyrefly check tapio_register` usable, which
# is how the pre-commit hook runs it.
_BANNER = (
    "# pyrefly: ignore-errors\n"
    "# Generated by `tapio-register generate` from\n"
    "# tapio_register/schema/term_register.yaml. Do not edit by hand.\n"
)


@dataclass(frozen=True)
class GeneratedArtifact:
    """One derived file and the text it should currently hold."""

    path: Path
    content: str


def _relative_to_service(content: str, schema: Path) -> str:
    """Rewrite the generating machine's absolute schema path to a repo-relative one.

    LinkML records the schema's ``source_file`` in the Pydantic module, as the
    absolute path it was generated from. Left alone, the checked-in artifact
    encodes one developer's checkout and ``--check`` fails everywhere else,
    including CI.
    """
    absolute = str(schema.resolve())
    try:
        relative = str(schema.resolve().relative_to(paths.SERVICE_DIR))
    except ValueError:
        return content
    return content.replace(absolute, relative)


def render_artifacts(schema_path: Path | None = None) -> list[GeneratedArtifact]:
    """Render every derived artifact in memory, without writing anything."""
    schema = schema_path or paths.SCHEMA_PATH
    pydantic_source = _relative_to_service(PydanticGenerator(str(schema)).serialize(), schema)
    json_schema = JsonSchemaGenerator(str(schema), top_class="TermRegister", not_closed=False).serialize()
    shapes = ShaclGenerator(str(schema), closed=True).serialize()
    return [
        GeneratedArtifact(paths.PYDANTIC_PATH, _ends_with_newline(_BANNER + pydantic_source)),
        # Reformatted so a diff on the checked-in copy is readable.
        GeneratedArtifact(paths.JSON_SCHEMA_PATH, json.dumps(json.loads(json_schema), indent=2) + "\n"),
        GeneratedArtifact(paths.SHACL_PATH, _ends_with_newline(shapes)),
    ]


def _ends_with_newline(content: str) -> str:
    """Keep generated files newline-terminated, so end-of-file fixers leave them alone."""
    return content if content.endswith("\n") else content + "\n"


def generate(schema_path: Path | None = None) -> list[Path]:
    """Write every derived artifact, returning the paths written."""
    paths.GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    init = paths.GENERATED_DIR / "__init__.py"
    if not init.exists():
        init.write_text('"""Artifacts generated from the LinkML schema. Do not edit by hand."""\n', encoding="utf-8")
    written = []
    for artifact in render_artifacts(schema_path):
        artifact.path.write_text(artifact.content, encoding="utf-8")
        written.append(artifact.path)
    return written


def _is_current(artifact: GeneratedArtifact) -> bool:
    if not artifact.path.exists():
        return False
    on_disk = artifact.path.read_text(encoding="utf-8")
    if artifact.path.suffix != ".ttl":
        return on_disk == artifact.content
    # rdflib does not order a shape's blank-node property lists deterministically,
    # so two runs of the same schema differ byte for byte while saying the same
    # thing. Compare the graphs instead, or the check fails at random.
    from rdflib import Graph
    from rdflib.compare import isomorphic

    return isomorphic(
        Graph().parse(data=on_disk, format="turtle"),
        Graph().parse(data=artifact.content, format="turtle"),
    )


def check_generated_is_current(schema_path: Path | None = None) -> list[Path]:
    """Return the derived artifacts that no longer match the schema.

    An empty list means the checked-in copies are current. CI runs this so a
    schema change cannot land without its generated artifacts.
    """
    return [artifact.path for artifact in render_artifacts(schema_path) if not _is_current(artifact)]
